// Permission types and constants based on RBAC model (ai/RBAC.md).
// Keep in sync with convex/lib/permissionsData.ts

export type PermissionLevel = 'FULL' | 'LIMITED' | 'VIEW' | 'NONE';

export type Module =
  | 'users'
  | 'roles'
  | 'properties'
  | 'staff'
  | 'reservations'
  | 'rooms'
  | 'fnb'
  | 'restaurant'
  | 'inventory'
  | 'finance'
  | 'financial'
  | 'reports'
  | 'system'
  | 'maintenance'
  | 'security'
  | 'expenses'
  | 'payroll';

export type Action =
  | 'create'
  | 'read'
  | 'update'
  | 'delete'
  | 'approve'
  | 'export'
  | 'admin'
  | 'settings'
  | 'audit';

export interface RolePermissions {
  [key: string]: PermissionLevel;
}

export type UserPermissions = Partial<Record<Module, PermissionLevel>>;
export type UserPermissionSet = UserPermissions | Record<string, boolean>;

export interface GranularPermission {
  module: Module;
  action: Action;
  resource?: string;
}

export const levelToActions: Record<PermissionLevel, Action[]> = {
  FULL: ['create', 'read', 'update', 'delete', 'approve', 'export', 'admin', 'settings', 'audit'],
  LIMITED: ['create', 'read', 'update'],
  VIEW: ['read'],
  NONE: [],
};

export const ROLE_PERMISSION_MATRIX: Record<string, UserPermissions> = {
  Administrator: {
    users: 'FULL',
    roles: 'FULL',
    properties: 'FULL',
    staff: 'FULL',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'FULL',
    finance: 'FULL',
    financial: 'FULL',
    reports: 'FULL',
    system: 'FULL',
    maintenance: 'FULL',
    security: 'FULL',
    payroll: 'FULL',
    expenses: 'FULL',
  },
  Director: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'FULL',
    staff: 'FULL',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'FULL',
    finance: 'FULL',
    financial: 'FULL',
    reports: 'FULL',
    system: 'LIMITED',
    maintenance: 'VIEW',
    security: 'VIEW',
    payroll: 'FULL',
    expenses: 'FULL',
  },
  'General Manager': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'LIMITED',
    staff: 'FULL',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'FULL',
    finance: 'FULL',
    financial: 'FULL',
    reports: 'FULL',
    system: 'NONE',
    maintenance: 'LIMITED',
    security: 'VIEW',
    payroll: 'FULL',
    expenses: 'FULL',
  },
  'Operations Manager': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'LIMITED',
    staff: 'LIMITED',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'FULL',
    finance: 'LIMITED',
    financial: 'LIMITED',
    reports: 'FULL',
    system: 'NONE',
    maintenance: 'FULL',
    security: 'VIEW',
    payroll: 'LIMITED',
    expenses: 'VIEW',
  },
  'Finance Manager': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'LIMITED',
    reservations: 'VIEW',
    rooms: 'VIEW',
    fnb: 'VIEW',
    restaurant: 'VIEW',
    inventory: 'VIEW',
    finance: 'FULL',
    financial: 'FULL',
    reports: 'FULL',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'VIEW',
    payroll: 'FULL',
    expenses: 'FULL',
  },
  'HR Manager': {
    users: 'LIMITED',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'FULL',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'NONE',
    restaurant: 'NONE',
    inventory: 'NONE',
    finance: 'LIMITED',
    financial: 'LIMITED',
    reports: 'LIMITED',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'FULL',
    expenses: 'NONE',
  },
  'IT Manager': {
    users: 'FULL',
    roles: 'FULL',
    properties: 'LIMITED',
    staff: 'LIMITED',
    reservations: 'LIMITED',
    rooms: 'LIMITED',
    fnb: 'LIMITED',
    restaurant: 'LIMITED',
    inventory: 'LIMITED',
    finance: 'LIMITED',
    financial: 'LIMITED',
    reports: 'FULL',
    system: 'FULL',
    maintenance: 'FULL',
    security: 'FULL',
    payroll: 'LIMITED',
    expenses: 'VIEW',
  },
  Manager: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'LIMITED',
    staff: 'FULL',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'FULL',
    finance: 'LIMITED',
    financial: 'LIMITED',
    reports: 'FULL',
    system: 'NONE',
    maintenance: 'LIMITED',
    security: 'NONE',
    payroll: 'LIMITED',
    expenses: 'VIEW',
  },
  'Assistant Manager': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'LIMITED',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'LIMITED',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'LIMITED',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'LIMITED',
    expenses: 'NONE',
  },
  Supervisor: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'LIMITED',
    reservations: 'LIMITED',
    rooms: 'LIMITED',
    fnb: 'FULL',
    restaurant: 'FULL',
    inventory: 'LIMITED',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'LIMITED',
    system: 'NONE',
    maintenance: 'LIMITED',
    security: 'NONE',
    payroll: 'LIMITED',
    expenses: 'NONE',
  },
  Receptionist: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'FULL',
    rooms: 'FULL',
    fnb: 'LIMITED',
    restaurant: 'LIMITED',
    inventory: 'NONE',
    finance: 'LIMITED',
    financial: 'LIMITED',
    reports: 'LIMITED',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  Concierge: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'LIMITED',
    rooms: 'LIMITED',
    fnb: 'NONE',
    restaurant: 'NONE',
    inventory: 'NONE',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'VIEW',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  Housekeeping: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'LIMITED',
    rooms: 'LIMITED',
    fnb: 'NONE',
    restaurant: 'NONE',
    inventory: 'NONE',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'LIMITED',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  Waiter: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'LIMITED',
    restaurant: 'LIMITED',
    inventory: 'NONE',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  Bartender: {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'FULL',
    restaurant: 'NONE',
    inventory: 'LIMITED',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  'Cook / Chef': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'NONE',
    restaurant: 'FULL',
    inventory: 'LIMITED',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  'Kitchen Assistant': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'NONE',
    restaurant: 'LIMITED',
    inventory: 'LIMITED',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  'Maintenance Staff': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'NONE',
    restaurant: 'NONE',
    inventory: 'NONE',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'FULL',
    security: 'NONE',
    payroll: 'NONE',
    expenses: 'NONE',
  },
  'Security Officer': {
    users: 'NONE',
    roles: 'NONE',
    properties: 'NONE',
    staff: 'NONE',
    reservations: 'NONE',
    rooms: 'NONE',
    fnb: 'NONE',
    restaurant: 'NONE',
    inventory: 'NONE',
    finance: 'NONE',
    financial: 'NONE',
    reports: 'NONE',
    system: 'NONE',
    maintenance: 'NONE',
    security: 'FULL',
    payroll: 'NONE',
    expenses: 'NONE',
  },
};

export const GRANULAR_PERMISSIONS = {
  reservations: {
    'reservations.view': 'reservations.read',
    'reservations.create': 'reservations.create',
    'reservations.update': 'reservations.update',
    'reservations.checkin': 'reservations.update',
    'reservations.checkout': 'reservations.update',
    'reservations.cancel': 'reservations.delete',
  },
  finance: {
    'finance.view': 'finance.read',
    'finance.charge': 'finance.create',
    'finance.refund': 'finance.update',
    'finance.reports': 'finance.read',
  },
  financial: {
    'financial.view': 'financial.read',
    'financial.charge': 'financial.create',
    'financial.refund': 'financial.update',
    'financial.reports': 'financial.read',
  },
  fnb: {
    'fnb.order.create': 'fnb.create',
    'fnb.order.manage': 'fnb.update',
    'fnb.menu.update': 'fnb.update',
  },
  restaurant: {
    'restaurant.order.create': 'restaurant.create',
    'restaurant.order.manage': 'restaurant.update',
    'restaurant.menu.update': 'restaurant.update',
  },
  payroll: {
    'payroll.employee.read': 'payroll.read',
    'payroll.employee.create': 'payroll.create',
    'payroll.employee.update': 'payroll.update',
    'payroll.timesheet.read': 'payroll.read',
    'payroll.timesheet.create': 'payroll.create',
    'payroll.timesheet.update': 'payroll.update',
    'payroll.timesheet.approve': 'payroll.update',
    'payroll.leave.read': 'payroll.read',
    'payroll.leave.create': 'payroll.create',
    'payroll.leave.approve': 'payroll.update',
    'payroll.run.read': 'payroll.read',
    'payroll.run.create': 'payroll.create',
    'payroll.run.calculate': 'payroll.update',
    'payroll.run.approve': 'payroll.approve',
    'payroll.run.export': 'payroll.export',
    'payroll.run.mark_paid': 'payroll.approve',
    'payroll.payslip.read': 'payroll.read',
    'payroll.settings.update': 'payroll.settings',
  },
  staff: {
    'staff.self.read': 'staff.read',
  },
  housekeeping: {
    'housekeeping.task.read': 'reservations.read',
    'housekeeping.task.assign': 'reservations.update',
    'housekeeping.task.update': 'reservations.update',
    'housekeeping.task.complete': 'reservations.update',
  },
  rooms: {
    'rooms.read': 'reservations.read',
    'rooms.update': 'reservations.update',
    'rooms.delete': 'reservations.delete',
  },
  maintenance: {
    'maintenance.order.read': 'maintenance.read',
    'maintenance.order.assign': 'maintenance.update',
    'maintenance.order.update': 'maintenance.update',
    'maintenance.order.complete': 'maintenance.update',
  },
  inventory: {
    'inventory.task.read': 'inventory.read',
    'inventory.task.assign': 'inventory.update',
    'inventory.task.update': 'inventory.update',
    'inventory.task.complete': 'inventory.update',
  },
  // Billing keys are explicit-only — see convex/lib/rolePermissionCatalog.ts
} as const;
